// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GiveMeHashFinal {
	
	
	public partial class searchPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label title;
		
		protected System.Web.UI.WebControls.TextBox hashBox;
		
		protected System.Web.UI.WebControls.Button findTweets;
		
		protected System.Web.UI.WebControls.TextBox filterBox;
		
		protected System.Web.UI.WebControls.Label sortBy;
		
		protected System.Web.UI.WebControls.DropDownList filter;
		
		protected System.Web.UI.WebControls.Literal Literal1;
	}
}
